controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
add-user:
  path: /register
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\UserController::createUser
  methods: POST
add-telegram:
  path: /telegram
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\TelegramController::sendSms